export default [
    {
        id: 1,
        title: "Victoria Peak",
        city: "Hong Kong",
        country: "Hong Kong",
        googleMaps: "https://goo.gl/maps/XT76C49rLhb6A2gH7",
        startDate: "15 April, 2017",
        endDate: "22 April, 2017",
        description: "Victoria Peak is a hill on the western half of Hong Kong Island. It is also known as Mount Austin, and locally as The Peak. With an elevation of 552 metres (1,811 ft). ",
        img: "hongkong.jpeg",
    },
    {
        id: 1,
        title: "Four Mile Beach",
        city: "Port Douglas",
        country: "Australia",
        googleMaps: "https://goo.gl/maps/yXGWcqS1ZtG7JZ2K6",
        startDate: "15 October, 2017",
        endDate: "22 October, 2017",
        description: "Port Douglas is a coastal town and locality in the Shire of Douglas, Queensland, approximately 60 km north of Cairns. In the 2016 census, Port Douglas had a population of 3,504 people.",
        img: "australia.jpeg",
        imgPin: "pin.png",
    },
    {
        id: 2,
        title: "Big Ben Tower",
        city: "London",
        country: "England",
        googleMaps: "https://goo.gl/maps/jaHSPPFDyYyhKjm97",
        startDate: "15 April, 2017",
        endDate: "22 April, 2017",
        description: "Big Ben is the nickname for the Great Bell of the striking clock at the north end of the Palace of Westminster in London, England, although the name is frequently extended to refer also to the clock and the clock tower.",
        img: "england.jpeg",
        imgPin: "pin.png",
    },
    {
        id: 3,
        title: "Gardens by the Bay",
        city: "Singapore",
        country: "Singapore",
        googleMaps: "https://goo.gl/maps/r2WH7VqfTDXvtqky5",
        startDate: "15 May, 2016",
        endDate: "22 May, 2016",
        description: "The Gardens by the Bay is a nature park spanning 101 hectares (250 acres) in the Central Region of Singapore, adjacent to the Marina Reservoir.",
        img: "singapore.jpeg",
        imgPin: "pin.png",
    },
    {
        id: 4,
        title: "The Great Jaguar Temple",
        city: "Tikal",
        country: "Guatemala",
        googleMaps: "https://goo.gl/maps/waAqKyATJeT8qoHW7",
        startDate: "15 June, 2009",
        endDate: "22 June, 2009",
        description: "Tikal Temple I is the designation given to one of the major structures at Tikal, one of the largest cities and archaeological sites of the pre-Columbian Maya civilization in Mesoamerica. It is located in the Petén Basin region of northern Guatemala. It also is known as the Temple of the Great Jaguar because of a lintel that represents a king sitting upon a jaguar throne.",
        img: "guatemala.jpeg",
        imgPin: "pin.png",
    },
    {
        id: 5,
        title: "Wat Yai Chaimongkhon",
        city: "Ayutthaya",
        country: "Thailand",
        googleMaps: "https://goo.gl/maps/kePBoBTjtyB6AK887",
        startDate: "15 August, 2018",
        endDate: "22 August, 2018",
        description: "Wat Yai Chai Mongkhon (Thai: วัดใหญ่ชัยมงคล) is a Buddhist temple in Ayutthaya, Thailand. The monastery was constructed by King U-Thong in 1357 AD to accommodate the monks that were ordained by Phra Wanratana Mahathera Burean.",
        img: "thailand.jpeg",
        imgPin: "pin.png",
    },
]
